version: '3.8'

services:
  gemini-key-checker:
    build: .
    container_name: gemini-key-checker
    ports:
      - "5000:5000"
    volumes:
      # 持久化数据库文件
      - ./data:/app/instance
      # 持久化日志文件
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
  logs: 