version: '3.8'

services:
  gemini-key-checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-key-checker
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # 持久化数据库文件
      - gemini_data:/app/instance
      # 可选：挂载配置文件（如果需要）
      # - ./config:/app/config:ro
    environment:
      # Flask环境变量
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/api/stats')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # 可选：资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  gemini_data:
    driver: local

# 可选：添加网络配置
networks:
  default:
    name: gemini-key-checker-network 